name = "RimuRealTime"
uuid = "40b165d5-aed3-424d-8ef0-7de3d6ea00bd"
authors = ["Joachim Brand <joachim.brand@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
Rimu = "c53c40cc-bd84-11e9-2cf4-a9fde2b9386e"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Rimu = "0.14.1"
TOML = "1.0.3"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
